# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8cc696724070845a6017776252ee6d3314364714665db195c647a490e9d80f67686a9d94c7f5a1b52f3751f1d1f8906b7f84a545126d2e46d12a48de8ff0855

test:
  secret_key_base: 97ad7c5944ed056d4003c89d986e6039ef48cbc5ff9377ac412840243c080efc698091bc3efbe749b2fa6a6c8857aed8e5b24b91c90ecf874d1544a31cd95f19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
